### ISSUE TITLE
About the tutorial example

### ISSUE THREAD

**Issue by mugpeng** [OSU-BMBL/scDEAL#3]
Hi,

It's a nice work! And congratulations to you.

I am trying to run the code in [OSU-BMBL/scDEAL: Deep Transfer Learning of Drug Sensitivity by Integrating Bulk and Single-cell RNA-seq data](https://github.com/OSU-BMBL/scDEAL)
I download all the code and data and create corresponding directories and run the code:
```
python bulkmodel.py --drug 'I-BET-762' --dimreduce 'AE' --encoder_h_dims "256,256" --predictor_h_dims "128,64" --bottleneck 256 --data_name 'GSE110894' --sampling 'SMOTE' --dropout 0.3 --printgene 'F' -mod 'new'
python scmodel.py --sc_data 'GSE110894' --dimreduce 'AE' --drug 'I-BET-762'  --bulk_h_dims "256,256" --bottleneck 256 --predictor_h_dims "128,64" --dropout 0.3 --printgene 'F' -mod 'new'
```
Even there is no error produced, there is also no output.

And I find a log error file:
```
 cat save/logs/transfer_2022-11-16-10-48-01.err
Traceback (most recent call last):
  File "/data1/bioteam_usr/yzpeng/2-software/biosoft/scDEAL-main/scmodel.py", line 794, in <module>
    run_main(args)
  File "/data1/bioteam_usr/yzpeng/2-software/biosoft/scDEAL-main/scmodel.py", line 337, in run_main
    adata = pp.read_sc_file(data_path)
  File "/data1/bioteam_usr/yzpeng/2-software/biosoft/scDEAL-main/scanpypip/preprocessing.py", line 52, in read_sc_file
    seperator = try_seperators(filename, header, index_col, separators)
  File "/data1/bioteam_usr/yzpeng/2-software/biosoft/scDEAL-main/scanpypip/preprocessing.py", line 38, in try_seperators
    first_row = pd.read_csv(filename, header=header, index_col=index_col, sep = s, nrows=1)
  File "/home/pengyz/miniconda3/envs/py3_glue/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/pengyz/miniconda3/envs/py3_glue/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "/home/pengyz/miniconda3/envs/py3_glue/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1538, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
```

What is the problem?

Thanks. And congratulation again.

**Comment by juychen** [comment]
Thanks, I will test the example and check the result

**Comment by juychen** [comment]
I suspect that this issue is related to #4. I have tried to fix it. Could you please pull the latest version and test it?
